services:
  - type: web
    name: ai-qa-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: SUPABASE_BUCKET
        value: "documents"
      - key: SESSION_SECRET
        generateValue: true
